---
- hosts: webservers
  remote_user: root
  roles:
  - { role: ansible-role-php }
  - { role: ansible-role-nginx }  
  tasks:
    # - name: Install (or update) docker.io
    #   apt:
    #     name: docker.io
    #     state: latest
    #     update_cache: yes
    #   when: env == "dev"  
    # - name: Intall pip
    #   easy_install: 
    #     name: pip
    #     state: latest
    - name: Ensure docker service started
      service:
        name: docker
        state: started
    - name: Container present
      docker_container:
        name: test